name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install gflags
      run: sudo apt install libgflags-dev
    - name: make solitaire
      run: make solitaire
    - name: make test
      run: make test

